language: java
jdk:
  - openjdk17
services:
  - postgresql
addons:
  postgresql: "16"
env:
  global:
    - PGPASSWORD=mypassword
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER myuser WITH PASSWORD 'mypassword';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO myuser;" -U postgres
notifications:
  email:
    recipients:
      - eric.binard.182@gmail.com
    on_success: always
    on_failure: always
