management:
  endpoints:
    web:
      expose: flyway
spring:
  data:
    rest:
      basePath: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  output:
    ansi:
      enabled: always
cloudinary:
  cloudName: ksams
  apiSecret: VuuLhGtP9qGbzz0mZqZjRsfccQc
  apiKey: 956677279662446

server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:ksams.p12
    key-store-password: M0n1erM-Less
    key-alias: ksams
    enabled: false
