management:
  endpoints:
    web:
      expose: flyway
spring:
  data:
    rest:
      basePath: /api
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

cloudinary:
  cloudName: ksams
  apiSecret: VuuLhGtP9qGbzz0mZqZjRsfccQc
  apiKey: 956677279662446
