management:
  endpoints:
    web:
      expose: flyway
spring:
  data:
    rest:
      basePath: /api

cloudinary:
  cloudName: ksams
  apiSecret: VuuLhGtP9qGbzz0mZqZjRsfccQc
  apiKey: 956677279662446