INSERT INTO ARMOR_CATEGORY (name) VALUES ('Silver');
INSERT INTO ARMOR (name, fk_category) VALUES ('Aquila', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541868/silver/aquila_wjzk5j.jpg', (select id from armor where name like 'Aquila'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Ophiuchus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541868/silver/ophiuchus_k9kdl1.jpg', (select id from armor where name like 'Ophiuchus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Lacerta', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541868/silver/lacerta_fm94oe.jpg', (select id from armor where name like 'Lacerta'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Cetus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541865/silver/cetus_z9khem.jpg', (select id from armor where name like 'Cetus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Canes Venatici', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541866/silver/canes_venatici_czy4yn.jpg', (select id from armor where name like 'Canes Venatici'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Centaurus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/centaurus_v49x0s.jpg', (select id from armor where name like 'Centaurus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Auriga', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541869/silver/auriga_i59jo4.jpg', (select id from armor where name like 'Auriga'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Cerberus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541868/silver/cerberus_yyxdhj.jpg', (select id from armor where name like 'Cerberus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Perseus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541865/silver/perseus_wolgzz.jpg', (select id from armor where name like 'Perseus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Canis Major', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/musca_ofhpeq.jpg', (select id from armor where name like 'Canis Major'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Musca', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/musca_ofhpeq.jpg', (select id from armor where name like 'Musca'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Hercules', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541866/silver/hercules_nwxrgp.jpg', (select id from armor where name like 'Hercules'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Sagitta', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541865/silver/sagitta_ctletk.gif', (select id from armor where name like 'Sagitta'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Cepheus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541865/silver/cepheus_usuhlu.gif', (select id from armor where name like 'Cepheus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Lyra', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541866/silver/lyra_pihgmf.jpg', (select id from armor where name like 'Lyra'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Cancer Minor', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541865/silver/cancer_minor_ltm8ju.jpg', (select id from armor where name like 'Cancer Minor'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Pavo', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/pavo_dx1mwh.gif', (select id from armor where name like 'Pavo'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Lotus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/lotus_fmffnb.jpg', (select id from armor where name like 'Lotus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Corvus', (select id from ARMOR_CATEGORY where name = 'Silver'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541867/silver/corvus_eywk4q.jpg', (select id from armor where name like 'Corvus'));
