INSERT INTO ARMOR_CATEGORY (name) VALUES ('Gold');
INSERT INTO ARMOR (name, fk_category) VALUES ('Aries', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541876/gold/aries_vlao8c.jpg', (select id from armor where name like 'Aries'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Taurus', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541876/gold/taurus_sdioml.jpg', (select id from armor where name like 'Taurus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Gemini', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/gemini_u9zpxe.jpg', (select id from armor where name like 'Gemini'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Cancer', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/cancer_jt99pc.jpg', (select id from armor where name like 'Cancer'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Leo', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541879/gold/leo_wayrve.png', (select id from armor where name like 'Leo'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Virgo', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/virgo_w2spvw.png', (select id from armor where name like 'Virgo'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Libra', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541876/gold/libra_ofndxp.jpg', (select id from armor where name like 'Libra'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Scorpius', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/scorpio_xwbnzo.jpg', (select id from armor where name like 'Scorpius'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Sagittarius', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/sagittarius_xp7inv.png', (select id from armor where name like 'Sagittarius'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Capricornus', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541879/gold/capricorn_ftmr31.jpg', (select id from armor where name like 'Capricornus'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Aquarius', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541877/gold/aquarius_bevbu1.png', (select id from armor where name like 'Aquarius'));
INSERT INTO ARMOR (name, fk_category) VALUES ('Pisces', (select id from ARMOR_CATEGORY where name = 'Gold'));
INSERT INTO ARMOR_VERSION (name, image, fk_armor) VALUES ('v1', 'https://res.cloudinary.com/ksams/image/upload/v1633541878/gold/pisces_xg7gkm.jpg', (select id from armor where name like 'Pisces'));
