ALTER TABLE ARMOR_CATEGORY ADD PRIMARY KEY (id);

ALTER TABLE STRENGTH ADD PRIMARY KEY (id);

CREATE TABLE ARMOR (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	fk_category SERIAL REFERENCES ARMOR_CATEGORY(id)
);

CREATE SEQUENCE armor_sequence START WITH 1 INCREMENT BY 1;