CREATE TABLE ARMOR_STRENGTH (
	id SERIAL PRIMARY KEY,
	amount INTEGER NOT NULL,
	fk_armor SERIAL REFERENCES ARMOR(id),
	fk_strength SERIAL REFERENCES STRENGTH(id)
);

CREATE SEQUENCE armor_strength_sequence START WITH 1 INCREMENT BY 1;